# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubUserDetails',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=300, null=True)),
                ('image_url', models.URLField(max_length=300, null=True)),
                ('url', models.URLField(max_length=300, null=True)),
                ('type', models.CharField(max_length=200, null=True)),
                ('score', models.DecimalField(decimal_places=4, default=0.0, max_digits=15)),
                ('no_of_repos', models.PositiveIntegerField(default=0, null=True)),
                ('no_of_followers', models.PositiveIntegerField(default=0, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=300, null=True)),
                ('created_date', models.DateField(null=True)),
                ('added_date', models.DateField(null=True)),
            ],
        ),
    ]
